# Generated by Django 6.0.4 on 2026-04-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_membership_customer_membership'),
    ]

    operations = [
    ]
